# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class DallascadSpiderItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    property_location_address = scrapy.Field()
    property_location_Neighborhood = scrapy.Field()
    property_location_Mapsco = scrapy.Field()
    owner = scrapy.Field()
    Owner_Name = scrapy.Field()
    Ownership_percentage = scrapy.Field()
    legal_Desc = scrapy.Field()
    value = scrapy.Field()
    Improvement = scrapy.Field()
    Land = scrapy.Field()
    Market_Value = scrapy.Field()
    Capped_Value = scrapy.Field()
    Revaluation_Year = scrapy.Field()
    Previous_Revaluation_Year = scrapy.Field()
    url = scrapy.Field()
    Residential_Account = scrapy.Field()
    Building_Class = scrapy.Field()
    Year_Built = scrapy.Field()
    Effective_Year_Built = scrapy.Field()
    Actual_Age = scrapy.Field()
    Desirability = scrapy.Field()
    Living_Area = scrapy.Field()
    Total_Area = scrapy.Field()
    Complete = scrapy.Field()
    Stories = scrapy.Field()
    Depreciation = scrapy.Field()
    Construction_Type = scrapy.Field()
    Foundation = scrapy.Field()
    Roof_Type = scrapy.Field()
    Roof_Material = scrapy.Field()
    Fence_Type = scrapy.Field()
    Ext_Wall_Material = scrapy.Field()
    Basement = scrapy.Field()
    Heating = scrapy.Field()
    Air_Condition = scrapy.Field()
    Baths_Full_Half = scrapy.Field()
    Kitchens = scrapy.Field()
    Bedrooms = scrapy.Field()
    Wet_Bars = scrapy.Field()
    Fireplaces = scrapy.Field()
    Sprinkler = scrapy.Field()
    Deck = scrapy.Field()
    Spa = scrapy.Field()
    Pool = scrapy.Field()
    Sauna = scrapy.Field()
    Improvement_Type = scrapy.Field()
    Construction = scrapy.Field()
    Floor = scrapy.Field()
    Exterior_Wall = scrapy.Field()
    Area_sqft = scrapy.Field()
    StateCode = scrapy.Field()
    Zoning = scrapy.Field()
    Frontage = scrapy.Field()
    Depth  = scrapy.Field()
    Area = scrapy.Field()
    Pricing_Method = scrapy.Field()
    UnitPrice = scrapy.Field()
    MarketAdjustment = scrapy.Field()
    AdjustedPrice = scrapy.Field()
    Ag_Land = scrapy.Field()
    City_Taxing_Jurisdiction = scrapy.Field()
    School_Taxing_Jurisdiction = scrapy.Field()
    County_and_School_Equalization_Taxing_Jurisdiction = scrapy.Field()
    College_Taxing_Jurisdiction = scrapy.Field()
    Hospital_Taxing_Jurisdiction = scrapy.Field()
    Special_District_Taxing_Jurisdiction = scrapy.Field()
    City_HOMESTEAD_EXEMPTION = scrapy.Field()
    School_HOMESTEAD_EXEMPTION = scrapy.Field()
    County_and_School_Equalization_HOMESTEAD_EXEMPTION = scrapy.Field()
    College_HOMESTEAD_EXEMPTIONHospital_HOMESTEAD_EXEMPTION = scrapy.Field()
    Special_District_HOMESTEAD_EXEMPTION = scrapy.Field()
    City_Taxable_Value = scrapy.Field()
    School_Taxable_Value = scrapy.Field()
    County_and_School_Equalization_Taxable_Value = scrapy.Field()
    College_Taxable_Value = scrapy.Field()
    Hospital_Taxable_Value = scrapy.Field()
    Special_District_Taxable_Value = scrapy.Field()
